--Proveedores que han vendido todas las piezas de color blanco.

select CODPRO FROM VENTAS V1 WHERE NOT EXISTS( ( SELECT CODPIE FROM PIEZAS WHERE TIPO='Blanco') MINUS ( SELECT CODPIE FROM VENTAS V2 WHERE V2.CODPRO = V1.CODPRO ) );


select CODPRO FROM PROVEEDOR P WHERE NOT EXISTS( ( SELECT CODPIE FROM PIEZAS WHERE TIPO='Blanco') MINUS ( SELECT CODPIE FROM VENTAS V2 WHERE V2.CODPRO = P.CODPRO ) );


--PROYECTOS DE lONDRES QUE HAN USADO TODAS LA PIEZAS VENDIDAS POR S3

SELECT CODPJ FROM PROYECTOS WHERE (CIUDAD = 'Londres') and not exists( (select CODPIE FROM VENTAS WHERE CODPRO='S3')minus(SELECT CODPIE FROM VENTAS WHERE VENTAS.CODPJ = PROYECTOS.CODPJ) );

describe user_tables;

select TABLE_NAME FROM USER_TABLES;

select TABLE_NAME FROM all_tables;

SELECT OWNER FROM ALL_TABLES;

DESCRIBE USER_TAB_COLUMNS;

select TABLE_NAME FROM USER_TAB_COLUMNS;

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS;

SELECT DATA_TYPE FROM USER_TAB_COLUMNS;

SELECT NULLABLE FROM USER_TAB_COLUMNS;

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_CONSTRAINTS;

SELECT * FROM USER_OBJECTS;



