--CREAR VISTA

create view VENTAS_BUENAS AS (SELECT CODPRO, CODPIE, CANTIDAD FROM VENTAS WHERE CANTIDAD >1000);

DESCRIBE USER_VIEWS;

DESCRIBE ALL_VIEWS;

SELECT * FROM ALL_VIEWS;

SELECT * FROM USER_VIEWS;

SELECT * FROM VENTAS_BUENAS;

SELECT * FROM VENTAS_BUENAS VB, PROVEEDOR P WHERE VB.CODPRO=P.CODPRO;

CREATE VIEW VENTAS_2015(proveedor, suma, media) AS(SELECT CODPRO, SUM(CANTIDAD) , AVG(CANTIDAD) FROM VENTAS WHERE TO_CHAR(fecha, 'yyyy')='2015' GROUP BY CODPRO);

select * from VENTAS_2015;

CREATE INDEX IND_PROVE ON PROVEEDOR(NOMPRO);

SELECT * FROM USER_INDEXES;

CREATE CLUSTER VENTA_PRO(CODPRO CHAR(3));

CREATE TABLE PROVEEDOR2(CODPRO char(3) primary key,NOMPRO varchar2(30) not null,STATUS number(2) CHECK(status>=1 and status<=10),CIUDAD varchar2(15)) CLUSTER VENTA_PRO(CODPRO);

CREATE TABLE VENTAS2(
CODPRO char(3) primary key,
NOMPRO varchar2(30) not null,
STATUS number(2) CHECK(status>=1 and status<=10),
CIUDAD varchar2(15)) CLUSTER VENTA_PRO(CODPRO);

CREATE INDEX CLUSTER_INDX ON CLUSTER VENTA_PRO;

